import { imagePath, placeholder } from './paths.js'
const path = imagePath + "appetizer images/";

const appetizers = {
    name: "Appetizers",
    items: [
        {
            number: "100",
            name: "Chicken Egg Drop",
            description: "",
            price: "2.20",
            image: path + "chicken egg drop soup.jpg",
        },
        {
            number: "101",
            name: "Miso Soup",
            description: "",
            price: "2.20",
            image: path + "miso soup.jpg",
        },
        {
            number: "102",
            name: "Small Salad",
            description: "",
            price: "2.20",
            image: path + "small salad.jpg",
        },
        {
            number: "138",
            name: "Deep Fried Softshell Crab",
            description: "",
            price: "11.95",
            image: placeholder,
        },
        {
            number: "137",
            name: "House Salad",
            description: "mixed vegetable with cucumber, avocado",
            price: "7.95",
            image: placeholder,
        },
        {
            number: "104",
            name: "Sunomono",
            description: "Cold Japanese noodle in sweet & sour sauce",
            price: "5.50",
            image: path + "ebi sunomono.jpg",
        },
        {
            number: "105",
            name: "Gomaae",
            description: "Spinach with sesame sauce",
            price: "5.25",
            image: placeholder,
        },
        {
            number: "106",
            name: "Seaweed Salad",
            description: "",
            price: "5.95",
            image: path + "seaweed salad.jpg",
        },
        {
            number: "107",
            name: "Edamame",
            description: "Green soy bean",
            price: "5.50",
            image: path + "edamame.jpg",
        },
        {
            number: "108",
            name: "Chicken Yakitori",
            description: "Skewers of chicken",
            price: "6.95",
            image: path + "chicken yakitori.jpg",
        },
        {
            number: "109",
            name: "Beef Tataki",
            description: "Rare sliced beef with ponzu sauce",
            price: "9.95",
            image: path + "beef tataki.jpg",
        },
        {
            number: "127",
            name: "Tuna Tataki",
            description: "Rare tuna with ponzu sauce",
            price: "13.99",
            image: path + "tuna tataki.jpg",
        },
        {
            number: "128",
            name: "Salmon Tataki",
            description: "Rare salmon with ponzu sauce",
            price: "13.99",
            image: path + "salmon tataki.jpg",
        },
        {
            number: "110",
            name: "Ika Karage",
            description: "Deep fried squid",
            price: "7.95",
            image: path + "ika karaage.jpg",
        },
        {
            number: "111",
            name: "Chicken Karaage",
            description: "Deep fried chicken",
            price: "7.50",
            image: path + "ika karaage.jpg",
        },
        {
            number: "112",
            name: "Agadeshi Tofu",
            description: "Deep fried tofu with tempura sauce",
            price: "6.25",
            image: path + "agedashi tofu.jpg",
        },
        {
            number: "113",
            name: "Gyoza",
            description: "Japanese style pork dumplings (6pcs)",
            price: "6.50",
            image: path + "gyoza.jpg",
        },
        {
            number: "114",
            name: "Spring Roll",
            description: "(4pcs)",
            price: "6.95",
            image: path + "spring roll.jpg",
        },
        {
            number: "115",
            name: "Oyster on Shell",
            description: "(6pcs)",
            price: "13.95",
            image: path + "oyster on shell.jpg",
        },
        {
            number: "116",
            name: "Salmon Kama",
            description: "BBQ salmon cheeck with ponzu sauce (3pcs)",
            price: "9.95",
            image: path + "salmon kama.jpg",
        },
        {
            number: "117",
            name: "Takoyaki",
            description: "Deep fried octopus ball (5pcs)",
            price: "7.50",
            image: placeholder,
        },
        {
            number: "120",
            name: "Shumai",
            description: "Deep fried shrimp dumpling (6pcs)",
            price: "7.50",
            image: placeholder,
        },
        {
            number: "123",
            name: "Saba",
            description: "BBQ mackerel with ponzu sauce",
            price: "9.95",
            image: path + "saba.jpg",
        },
        {
            number: "131",
            name: "BBQ Squid",
            description: "",
            price: "11.95",
            image: placeholder,
        },
        {
            number: "132",
            name: "Deep Fried Fish Balls",
            description: "(8pcs)",
            price: "5.95",
            image: placeholder,
        },
        {
            number: "133",
            name: "BBQ Lamb",
            description: "",
            price: "5.95",
            image: placeholder,
        },
        {
            number: "134",
            name: "Chicken Katsu",
            description: "",
            price: "6.95",
            image: path + "chicken katsu.jpg",
        },
        {
            number: "135",
            name: "Pork Katsu",
            description: "",
            price: "6.95",
            image: path + "pork katsu.jpg",
        },
        {
            number: "215",
            name: "Yam Fries",
            description: "",
            price: "6.50",
            image: placeholder,
        },
    ]
}

export { appetizers };