import { imageFolderPath, placeholder } from './paths.js'
const path = imageFolderPath + "appetizer images/";

const appetizers = {
    name: "Appetizers",
    items: [
        {
            number: "100",
            name: "Rice",
            description: "",
            price: "2.30",
            image: placeholder,
        },
        {
            number: "101",
            name: "Miso Soup",
            description: "",
            price: "3.09",
            image: path + "miso soup.jpg",
        },
        {
            number: "102",
            name: "Small Salad",
            description: "",
            price: "3.09",
            image: path + "small salad.jpg",
        },
        {
            number: "138",
            name: "Deep Fried Soft Shell Crab",
            description: "",
            price: "15.95",
            image: path + "deep fried soft shell crab.jpg",
        },
        {
            number: "137",
            name: "Avocado Salad",
            description: "mixed vegetable with cucumber, avocado",
            price: "13.95",
            image: path + "house salad.jpg",
        },
        {
            number: "104",
            name: "Sunomono",
            description: "Cold Japanese noodle in sweet & sour sauce",
            price: "6.99",
            image: path + "ebi sunomono.jpg",
        },
        {
            number: "105",
            name: "Gomaae",
            description: "Spinach with sesame sauce",
            price: "6.85",
            image: placeholder,
        },
        {
            number: "106",
            name: "Seaweed Salad",
            description: "",
            price: "6.99",
            image: path + "seaweed salad.jpg",
        },
        {
            number: "107",
            name: "Edamame",
            description: "Green soy bean",
            price: "6.75",
            image: path + "edamame.jpg",
        },
        {
            number: "108",
            name: "Chicken Yakitori",
            description: "Skewers of chicken",
            price: "8.75",
            image: path + "chicken yakitori.jpg",
        },
        {
            number: "109",
            name: "Beef Tataki",
            description: "Rare sliced beef with ponzu sauce",
            price: "12.99",
            image: path + "beef tataki.jpg",
        },
        {
            number: "127",
            name: "Tuna Tataki",
            description: "Rare tuna with ponzu sauce",
            price: "17.99",
            image: path + "tuna tataki.jpg",
        },
        {
            number: "128",
            name: "Salmon Tataki",
            description: "Rare salmon with ponzu sauce",
            price: "17.99",
            image: path + "salmon tataki.jpg",
        },
        {
            number: "110",
            name: "Ika Karage",
            description: "Deep fried squid",
            price: "8.99",
            image: path + "ika karaage.jpg",
        },
        {
            number: "111",
            name: "Chicken Karaage",
            description: "Deep fried chicken",
            price: "8.79",
            image: path + "chicken karaage.jpg",
        },
        {
            number: "112",
            name: "Agadeshi Tofu",
            description: "Deep fried tofu with tempura sauce",
            price: "6.99",
            image: path + "agedashi tofu.jpg",
        },
        {
            number: "113",
            name: "Gyoza",
            description: "Japanese style pork dumplings (6pcs)",
            price: "7.99",
            image: path + "gyoza.jpg",
        },
        {
            number: "114",
            name: "Spring Roll",
            description: "Veggie spring roll (4pcs)",
            price: "8.19",
            image: path + "spring roll.jpg",
        },
        {
            number: "116",
            name: "Salmon Kama",
            description: "BBQ salmon cheeck with ponzu sauce (3pcs)",
            price: "13.95",
            image: path + "salmon kama.jpg",
        },
        {
            number: "117",
            name: "Takoyaki",
            description: "Deep fried octopus ball (5pcs)",
            price: "8.99",
            image: path + "takoyaki.jpg",
        },
        {
            number: "120",
            name: "Shumai",
            description: "Deep fried shrimp dumpling (6pcs)",
            price: "8.99",
            image: placeholder,
        },
        {
            number: "123",
            name: "Saba",
            description: "BBQ mackerel with ponzu sauce",
            price: "12.99",
            image: path + "saba.jpg",
        },
        {
            number: "131",
            name: "BBQ Squid",
            description: "",
            price: "15.99",
            image: placeholder,
        },
        {
            number: "132",
            name: "Deep Fried Fish Balls",
            description: "(8pcs)",
            price: "8.49",
            image: placeholder,
        },
        {
            number: "133",
            name: "BBQ Lamb",
            description: "",
            price: "7.49",
            image: placeholder,
        },
        {
            number: "134",
            name: "Chicken Katsu",
            description: "Breaded and deep fried chicken",
            price: "8.99",
            image: path + "chicken katsu.jpg",
        },
        {
            number: "135",
            name: "Pork Katsu",
            description: "Breaded and deep fried pork",
            price: "8.99",
            image: path + "pork katsu.jpg",
        },
        {
            number: "215",
            name: "French Fries",
            description: "",
            price: "7.99",
            image: placeholder,
        },
    ]
}

export { appetizers };