import { imageFolderPath, placeholder } from './paths.js'
const path = imageFolderPath + "combos images/";

const combos = {
    name: "Combos",
    items: [
        {
            number: "500",
            name: "Sushi & Sashimi",
            description: "",
            price: "22.95",
            image: placeholder,
        },
        {
            number: "501",
            name: "Maki Combo",
            description: "Cali roll, salmon roll, avocado with kappa roll, 2pcs outsider roll",
            price: "13.95",
            image: placeholder,
        },
        {
            number: "502",
            name: "Assorted Sushi",
            description: "Salmon x2, tuna x2, ebi, toro, hamachi, special scallop, cali roll, 2pcs outsider roll",
            price: "22.95",
            image: placeholder,
        },
        {
            number: "503",
            name: "Assorted Sashimi",
            description: "Salmon x3, tuna x3, red tuna x2, hamachi x2, scallop x2",
            price: "24.95",
            image: placeholder,
        },
        {
            number: "504",
            name: "Love Boat",
            description: "Comes with soup & salad for 2",
            price: "41.95",
            image: placeholder,
        },
        {
            number: "505",
            name: "Boat Deluxe",
            description: "Comes with soup & salad for 2",
            price: "44.95",
            image: placeholder,
        },
        {
            number: "506",
            name: "Dinner for Two",
            description: "Comes with soup & salad for 2",
            price: "32.95",
            image: placeholder,
        },
        {
            number: "507",
            name: "Dinner for Four",
            description: "Comes with soup & salad for 4",
            price: "68.95",
            image: placeholder,
        },
        {
            number: "508",
            name: "Salmon Lover's Combo",
            description: "salmon sashimi x6, salmon sushi x6, salmon avocado roll, spicy salmon roll",
            price: "32.95",
            image: placeholder,
        },
        {
            number: "509",
            name: "Ichiban Boat of Maki Rolls",
            description: "Fitness roll, tempura roll, california roll, outsider roll, salmon roll, spicy tuna roll, avocado roll",
            price: "55.95",
            image: placeholder,
        },
        {
            number: "521",
            name: "Roll Group",
            description: "70pcs",
            price: "66.95",
            image: placeholder,
        },
        {
            number: "522",
            name: "Sushi Group",
            description: "48pcs",
            price: "83.95",
            image: placeholder,
        },
        {
            number: "523",
            name: "Dinner Boat for Four",
            description: "Served with soup & salad, tempura, chicken katsu, sushi & sashimi",
            price: "50.95",
            image: placeholder,
        },
        {
            number: "524",
            name: "Special Dinner Boat for Six",
            description: "Served with soup & salad, tempura, chicken, beef, spring roll, gyoza, sushi & sashimi",
            price: "99.95",
            image: placeholder,
        },
        // MATTHEW SPLIT MENU SECTION HERE?
        {
            number: "510",
            name: "Salmon Sashimi",
            description: "6pcs",
            price: "11.99",
            image: path + "salmon sashimi.jpg",
        },
        {
            number: "511",
            name: "Tuna & Salmon Sashimi",
            description: "6pcs",
            price: "11.99",
            image: placeholder,
        },
        {
            number: "512",
            name: "Toro Sashimi",
            description: "6pcs",
            price: "14.99",
            image: placeholder,
        },
        {
            number: "513",
            name: "Red Tuna Sashimi",
            description: "6pcs",
            price: "18.99",
            image: placeholder,
        },
        {
            number: "514",
            name: "Hamachi Sashimi",
            description: "6pcs",
            price: "17.99",
            image: placeholder,
        },
        {
            number: "515",
            name: "Spicy Tuna Sashimi",
            description: "6pcs",
            price: "12.99",
            image: placeholder,
        },
        {
            number: "516",
            name: "Spicy Salmon Sashimi",
            description: "6pcs",
            price: "12.99",
            image: placeholder,
        },
        {
            number: "517",
            name: "Spicy Toro Sashimi",
            description: "6pcs",
            price: "14.99",
            image: placeholder,
        },
        {
            number: "518",
            name: "Smoked Salmon Sashimi",
            description: "6pcs",
            price: "13.99",
            image: placeholder,
        },
        {
            number: "519",
            name: "Tuna Sashimi",
            description: "6pcs",
            price: "11.99",
            image: path + "tuna sashimi.jpg",
        },
    ]
}

export { combos };