import { imageFolderPath, placeholder, } from "./paths.js";
const path = imageFolderPath + "nigiri images/";

const nigiri = {
    name: "Nigiri and Sashimi",
    items:  [
        {
            number: "1",
            name: "Ebi",
            description: "Prawn (steamed)",
            price: "1.99",
            image: path + "ebi.jpg",
        },
        {
            number: "2",
            name: "Ebi (Special)",
            description: "Prawn, imitation crab, seaweed, mayo, cayenne pepper",
            price: "2.30",
            image: path + "ebi special.jpg",
        },
        {
            number: "3",
            name: "Hamachi",
            description: "Yellow tail",
            price: "3.15",
            image: placeholder,
        },
        {
            number: "4",
            name: "Hotategai",
            description: "Scallop",
            price: "2.45",
            image: placeholder,
        },
        {
            number: "5",
            name: "Hotategai (Special)",
            description: "Scallop, imitation crab, tobiko, mayo",
            price: "2.30",
            image: placeholder,
        },
        {
            number: "6",
            name: "Ikura",
            description: "Salmon roe",
            price: "2.80",
            image: path + "ikura.jpg",
        },
        {
            number: "7",
            name: "Inari",
            description: "Fried bean curd",
            price: "1.99",
            image: path + "inari.jpg",
        },
        {
            number: "8",
            name: "Maguro",
            description: "Tuna",
            price: "1.99",
            image: placeholder,
        },
        {
            number: "9",
            name: "Spicy Tuna",
            description: "Chopped tuna with house sauce",
            price: "2.25",
            image: path + "spicy tuna.jpg",
        },
        {
            number: "10",
            name: "Masago",
            description: "Capelin roe",
            price: "2.30",
            image: path + "masago.jpg",
        },
        {
            number: "11",
            name: "Sake",
            description: "Raw salmon",
            price: "1.99",
            image: placeholder,
        },
        {
            number: "12",
            name: "Sake (Smoked)",
            description: "Smoked salmon",
            price: "2.45",
            image: placeholder,
        },
        {
            number: "13",
            name: "Tamago",
            description: "Sweetend omelette",
            price: "1.99",
            image: path + "tamago.jpg",
        },
        {
            number: "14",
            name: "Tobiko",
            description: "Flying fish roe",
            price: "2.30",
            image: path + "tobiko.jpg",
        },
        {
            number: "15",
            name: "Toro",
            description: "Belly of tuna",
            price: "2.50",
            image: path + "toro.jpg",
        },
        {
            number: "16",
            name: "Unagi",
            description: "Fresh water eel (broiled)",
            price: "2.80",
            image: path + "unagi.jpg",
        },
        {
            number: "17",
            name: "Red Tuna",
            description: "Ahi Tuna",
            price: "3.15",
            image: placeholder,
        },
        {
            number: "20",
            name: "Hokkigai",
            description: "Surf clam",
            price: "1.99",
            image: path + "hokkigai.jpg",
        },
        {
            number: "21",
            name: "Ika",
            description: "Squid",
            price: "1.99",
            image: path + "ika.jpg",
        },
        {
            number: "23",
            name: "Saba",
            description: "Mackerel",
            price: "1.99",
            image: path + "saba.jpg",
        },
        {
            number: "25",
            name: "Tako",
            description: "Octopus (steamed)",
            price: "2.25",
            image: path + "tako.jpg",
        },
        {
            number: "26",
            name: "Tai",
            description: "Red snapper",
            price: "1.99",
            image: path + "tai.jpg",
        },
    ]
}

export { nigiri };